version: '3'
networks:
  gis:
services:
  gisdata:
    image: registry.support.hub.ics.perm.ru/rgis-perm-postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      RGIS_LOAD_FULL_DATA: "true"
    networks:
      - gis
  webapp:
    image: "ol4webapp:latest"
    build: ./webapp
    environment:
      DB_ADDR: gisdata
      DB_NAME: rgispk
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "8080:8080"
    networks:
      - gis